CREATE TABLE IF NOT EXISTS `users` (
    `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(100) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `level` TINYINT UNSIGNED NOT NULL
) ENGINE = InnoDB CHARSET=utf8;
